# Generated by Django 4.2.13 on 2024-06-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=18, verbose_name='密码')),
                ('email', models.EmailField(max_length=30, verbose_name='邮箱')),
                ('age', models.IntegerField(default=18, verbose_name='年龄')),
            ],
            options={
                'verbose_name': '用户表',
                'db_table': 'user',
            },
        ),
    ]
