# Generated by Django 4.2.13 on 2024-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp', models.CharField(max_length=300, verbose_name='机构名')),
                ('mid', models.CharField(max_length=300, verbose_name='商户id')),
                ('data', models.TextField(verbose_name='文本数据')),
                ('time', models.DateTimeField(verbose_name='获取时间')),
            ],
            options={
                'verbose_name': '存储接受到的响应数据',
                'db_table': 'result',
            },
        ),
    ]
