# Generated by Django 4.2.13 on 2024-06-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_resultbody'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': '文件存储',
                'db_table': 'files',
            },
        ),
    ]
